name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    # Checkout xmrig repo
    - uses: actions/checkout@v2

    # Cache build dir and dependencies
    - name: Cache build directory and deps
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}\build
          ${{github.workspace}}\xmrig-deps
        key: ${{ runner.os }}-build
    
    # Checkout xmrig dependencies repo
    - uses: actions/checkout@v2
      with:
        repository: xmrig/xmrig-deps
        path: xmrig-deps # This puts the repo contents in ${{github.workspace}}/xmrig-deps/*

    # Create build dir
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}\build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      working-directory: ${{github.workspace}}\build
      run: cmake ${{github.workspace}}\build\.. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=${{github.workspace}}\xmrig-deps\msvc2019\x64
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    # Upload build output
    - uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ${{github.workspace}}/build/Release/
      